name: 'Hide Pull Request Comment'
branding:
  icon: 'message-circle'
  color: 'grey-dark' 
description: 'hide a comment on a pull request'
inputs:
  message:
    description: 'Message that should be printed in the pull request'
    required: false
  GITHUB_TOKEN:
    description: 'Github token of the repository (automatically created by Github)'
    required: true
  pr_number:
    description: 'Manual pull request number'
runs:
  using: 'node16'
  main: 'lib/index.js'
